version: "3.9"
services:
  db:
    image: postgres:15
    container_name: realworld-db
    restart: always
    environment:
      POSTGRES_USER: realworld
      POSTGRES_PASSWORD: realworld123
      POSTGRES_DB: realworld_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

